// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// discretize_cpp
NumericMatrix discretize_cpp(DataFrame data, NumericVector dims, NumericVector x_range, NumericVector y_range);
RcppExport SEXP _discretizer_discretize_cpp(SEXP dataSEXP, SEXP dimsSEXP, SEXP x_rangeSEXP, SEXP y_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_range(x_rangeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_range(y_rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(discretize_cpp(data, dims, x_range, y_range));
    return rcpp_result_gen;
END_RCPP
}
// strange_attractor_cpp
List strange_attractor_cpp(NumericVector a, int n, double x0, double y0);
RcppExport SEXP _discretizer_strange_attractor_cpp(SEXP aSEXP, SEXP nSEXP, SEXP x0SEXP, SEXP y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type y0(y0SEXP);
    rcpp_result_gen = Rcpp::wrap(strange_attractor_cpp(a, n, x0, y0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_discretizer_discretize_cpp", (DL_FUNC) &_discretizer_discretize_cpp, 4},
    {"_discretizer_strange_attractor_cpp", (DL_FUNC) &_discretizer_strange_attractor_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_discretizer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
