# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

discretize_cpp <- function(data, dims, x_range, y_range) {
    .Call(`_discretizer_discretize_cpp`, data, dims, x_range, y_range)
}

strange_attractor_cpp <- function(a, n, x0, y0) {
    .Call(`_discretizer_strange_attractor_cpp`, a, n, x0, y0)
}

